version: '3.8'

services:
  epu_ucms_backend:
    image: epu_ucms_backend:v1.0
    container_name: epu_ucms_backend
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    tty: true
    restart: always

  redis:
    image: redis:latest
    restart: always